= SICK Visionary samples
:toclevels: 4
:source-highlighter: rouge
:icons: font
:toc:

== Overview

This repository contains programming samples for Sick Visionary-T Mini CX (pass:[V3S105-1AAAAAA]) and Sick Visionary-S CX (pass:[V3S102-1AAAAAA] and pass:[V3S102<area>-1AABAAB]).

The entry point for our camera programming samples is the link:visionary_welcome/python/welcome.py[Python Welcome Demo] and the link:visionary_welcome/cpp/welcome.cpp[Cpp Welcome Demo]. These welcome demos provide an overview to the functionalities offered by the Visionary Python and C++ API. They cover aspects such as device connection, user authentication (login and logout), parameter adjustments, along with the streaming and storage of images and point clouds.

For new users we recommended to follow the samples in the following order:

. link:finding_and_connecting_devices/readme.adoc[Finding and connecting devices]
. link:userlevels_and_passwords/readme.adoc[Userlevels and passwords]
. link:diagnosing_devices/readme.adoc[Diagnosing devices]
. link:image_frontend_configuration/readme.adoc[Image frontend configuration]
. link:image_streaming_and_storing/readme.adoc[Streaming and storing]
. link:/TODO[Time synchronization]

== License

The source code is released under link:./LICENSE[The Unlicense].

== Supported environments

The samples in this repository have been tested with the following platforms:

[cols="1,1,1,1", options="header"]
|===
| **Platform**
| **Compiler**
| **Version**
| **Notes**

| Windows
| Visual Studio / Build Tools
| 2022 (MSVC = 19.3x)
|

| Windows
| gcc (mingw64)
| 14.2.0 (>= 11.1)
|

| Linux inside WSL2
| gcc
| 11.4.0 (>= 11.1)
| finding_and_connecting_devices (AutoIP) and image_streaming_and_storing (UDP) will not work with default WSL2 configuration (NAT)

|===


== Supported Hardware

[cols="1,1,1,1", options="header"]
|===
| **device name**
| **part no.**
| **description**
| **firmware version**

| Visionary-T Mini CX (pass:[V3S105-1AAAAAA], pass:[V3S105-1AAAAAD])
| link:https://www.sick.com/1112649[1112649] link:https://www.sick.com/1132065[1132065]
| 3D time-of-flight camera
| 2.1.0 & 3.0.0 & 3.0.1 ✔

| Visionary-S CX (pass:[V3S102-1AAAAAA], pass:[V3S102<area>-1AABAAB])
| link:https://www.sick.com/1090184[1090184] link:https://www.sick.com/1090185[1090185]
| 3D structured light stereovision camera with RGB data
| 6.0.0 & 6.5.0 ✔
|===


== Getting started

Ensure you have a recent version of https://cmake.org/install/[cmake] footnote:[minimum required version >= 3.24]
and a compiler available on your machine's system.
If you are working on windows with a recent version of VisualStudiofootnote:[>= 2017, or buildtools with MSVC = 14.x],
take care to have a CMake version supporting your version of Visual Studio.

After cloning this repository, open a Command Prompt window and navigate to `sick_visionary_samples` directory. Run these additional git commands to have the correct submodules in place
footnote:[Only necessary if you have fetched the files from the GitHub repository. If you have received the samples in a prepared package, the git commands can be skipped.]:

* `git submodule update --init --recursive`

=== Python

Before you begin, ensure you have met the following requirements:

* You have installed `pip`, which is a package manager for Python. If not, you can install it using the following command:

[source,shell]
----
$ sudo apt install python3-pip
----

* You have installed the following Python libraries: `OpenCV`, `NumPy`, and `CryptodomeX`. If not, you can install them using pip:

[source,shell]
----
$ pip3 install opencv-python
$ pip3 install numpy
$ pip3 install pycryptodomex
----

[NOTE]
====
Please replace the installation commands with the appropriate ones for your operating system or Python environment if necessary.
====

To run the Python welcome demo, execute the following command from the top-level directory:

[source,bash]
----
python3 -m visionary_welcome.python.welcome -i192.168.1.10 -dVisionary-S
----

Depending on your environment, you may need to use `python` or `python3`. Remember to adjust the IP address (`-i`) and device type (`-d`) to match your specific device.

=== C++

To build the C++ samples, it is suggested to proceed like this
footnote:[Also, other ways are possible]:

* `cmake -B build` optionally also specify other options like -G for custom generator

[NOTE]
====
If you run into WARNING_AS_ERROR issue with some compiler (which is enabled per default) just use the cmake override ```--compile-no-warning-as-error``` when configuring the project.
====

Now you can build the files with the chosen build-system you've generated them for,
for instance, open the solution in VisualStudio or run make/ninja.

* `cmake --build build`

To run the C++ welcome demo, follow these steps:

. Navigate to the `build/` directory from the top-level directory:

[source,bash]
----
$ cd build/
----

. Execute the `welcome` demo with the specified IP address and device:

[source,bash]
----
$ ./welcome -i127.0.0.1 -dVisionary-S
----
Remember to adjust the IP address (`-i`) and device type (`-d`) to match your specific device.

== Support

Depending on the nature of your question, there are two support channels:

1. For questions regarding the code shared in this repo please check the FAQ first and link:../../issues[search if an issue already exists]. If a related issue doesn't exist, you can open a new issue using the link:../../issues/new/choose[issue form].
2. For application or device specific questions look for common solutions and knowledge articles on the link:https://support.sick.com/[Sick Support Portal]. If your question is not answered there, open a ticket on the link:https://support.sick.com/[Sick Support Portal].

== Keywords

Visionary-S
Visionary-T Mini
SICK
CX
